name: container_ship
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.3
  retrofit: ^4.0.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  dio: ^5.3.3
  riverpod_annotation: ^2.3.0

dev_dependencies:
  freezed: ^2.4.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.0
  custom_lint: ^0.5.3
  riverpod_lint: ^2.3.3
  riverpod_generator: ^2.3.5
  mocktail: ^1.0.1
  golden_toolkit: ^0.15.0


flutter:
  uses-material-design: true

        
    
    
                                      